version: '3.8'
services:

  postgres: # bitnami-container images alludes to being  up-to-date, bare-minimum, and non-root which comes with an additional security layer, so let's give it a shot
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-password
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
        interval: 10s
        timeout: 10s
        retries: 5
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    secrets:
      - pg-password

  aggregator:
    build:
      context: ./OSItemIndex.Aggregators
      dockerfile: aggregator.dockerfile
    env_file: .env
    secrets:
      - source: pg-password
        target: DbOptions__DbPass # Allows easy mapping to the DbOptions DbPass prop by utilizing the key-per-file configuration provider
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M

secrets:
  pg-password:
    file: ./secrets/pg-password
