version: '3.8'
services:

  traefik:
    image: traefik
    container_name: osi-traefik
    command:
      - --api=false
      - --api.dashboard=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false # exposes services by default if true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - '80:80' # HTTP port
      - '443:443' # HTTPS port
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro' # docker api socket

  postgres:
    image: supabase/postgres:latest
    container_name: osi-postgres
    env_file: .env
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ] # runs a shell command to check if the postgres server is ready - https://www.postgresql.org/docs/current/app-pg-isready.html
        interval: 10s
        timeout: 10s
        retries: 5
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    labels:
      - traefik.enable=true
      - traefik.http.routers.postgres.tls=true
      - traefik.http.routers.postgres.rule=Host(`postgres.${WEB_DOMAIN}`)
    tmpfs:
      - '/var/lib/postgresql/data' # prevent data persistence
    volumes:
      - './create-publication.sql:/docker-entrypoint-initdb.d/create-publication.sql'

  realtime:
    image: supabase/realtime:latest
    container_name: osi-postgres-realtime
    environment:
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT}
      PORT: 5000
      JWT_SECRET: ${REALTIME_JWT}
      SECURE_CHANNELS: 'true'
    ports:
      - '23400:5000'
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.realtime.tls=true
      - traefik.http.routers.realtime.rule=Host(`${WEB_DOMAIN}`) && PathPrefix(`/socket`)

  api:
    container_name: osi-api
    image: ghcr.io/ositemindex/ositemindex.api:latest
    env_file: .env
    environment:
      DbOptions__DbHost: postgres
      DbOptions__DbUser: ${POSTGRES_USER}
      DbOptions__DbPass: ${POSTGRES_PASSWORD}
      DbOptions__DbPort: ${POSTGRES_PORT}
      DbOptions__DbDatabase: ${POSTGRES_DB}
    ports:
      - '23401:5000'
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.priority=1
      - traefik.http.routers.api.rule=Host(`${WEB_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/swagger`))

  aggregator:
      container_name: osi-aggregator
      image: ghcr.io/ositemindex/ositemindex.aggregator:latest
      env_file: .env
      environment:
        DbOptions__DbHost: postgres
        DbOptions__DbUser: ${POSTGRES_USER}
        DbOptions__DbPass: ${POSTGRES_PASSWORD}
        DbOptions__DbPort: ${POSTGRES_PORT}
        DbOptions__DbDatabase: ${POSTGRES_DB}
      ports:
        - '23402:5000'
      deploy:
        resources:
          limits:
            memory: 512M
      depends_on:
        api:
          condition: service_started
        realtime:
          condition: service_started
        postgres:
          condition: service_healthy
      labels:
        - traefik.enable=true
        - traefik.http.routers.aggregator.tls=true
        - traefik.http.routers.aggregator.priority=0
        - traefik.http.routers.aggregator.rule=Host(`${WEB_DOMAIN}`) && PathPrefix(`/api/services`)
