name: Publish docker packages

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [publish-all]

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    strategy:
      matrix:
        include:
          - repo: ositemindex.api
          - repo: ositemindex.aggregator
    steps:
      - name: Dispatch build-publish [${{ matrix.repo }}]
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ositemindex
          repo: ${{ matrix.repo }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: build-publish-dockerfile.yml
