name: Publish docker packages

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    strategy:
      matrix:
        repo: ['ositemindex.api', 'ositemindex.aggregator']
        repoUpper: ['OSItemIndex.API', 'OSItemIndex.Aggregator']
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ositemindex/${{ matrix.repo }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          context: ./OSItemIndex/OSItemIndex/${{ matrix.repoUpper }}
          tags: |
            ghcr.io/ositemindex/${{ matrix.repo }}:${{ github.ref }}
            ghcr.io/ositemindex/${{ matrix.repo }}:latest